version: '3.8'

services:
  khamar-khata:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: khamar_khata_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-http-header-size=65536
      - DATABASE_URL=${DATABASE_URL:-postgresql://shenron:abirmallik76922247@100.124.204.9:5432/main_db}
      - AUTH_SECRET=${AUTH_SECRET:-5165554ca9d91627615dee993e9b545a9f69607f406b4cead67d5f72e4b83348}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-https://abirmallik11.tail100a66.ts.net/khamar_khata/api/auth}
      - AUTH_URL=${AUTH_URL:-https://abirmallik11.tail100a66.ts.net/khamar_khata/api/auth}
      - AUTH_TRUST_HOST=true
      - UPLOAD_DIR=/app/public/uploads
    volumes:
      - khamar_khata_uploads:/app/public/uploads

volumes:
  khamar_khata_uploads:
    driver: local
