import { createClient } from '@/utils/supabase/server'
import { ReportsUI } from './ReportsUI'
import { BarChart3 } from 'lucide-react'

export default async function ReportsPage(props: {
  searchParams: Promise<{ start?: string; end?: string; range?: string }>
}) {
  const searchParams = await props.searchParams;
  const supabase = await createClient()

  const startDate = searchParams.start || undefined
  const endDate = searchParams.end || undefined

  const { data: { user } } = await supabase.auth.getUser()
  
  const [
    { data, error },
    { data: equityData }
  ] = await Promise.all([
    supabase.rpc('get_farm_reports', {
      p_start_date: startDate,
      p_end_date: endDate
    }),
    (supabase as any).rpc('get_partner_equity_report', {
      p_user_id: user!.id
    })
  ])

  if (error) {
    console.error('Error fetching reports:', error)
    return (
      <div className="p-8 text-center bg-red-50 text-red-600 rounded-md">
        <p className="font-bold">Failed to load report data.</p>
        <p className="text-sm mt-1">{error.message}</p>
      </div>
    )
  }

  return (
    <div className="flex flex-col gap-8 max-w-5xl mx-auto w-full pb-20">
      <header className="flex flex-col md:flex-row md:items-end justify-between gap-4 print:hidden">
        <div>
          <div className="flex items-center gap-3 mb-1">
            <div className="p-2 bg-(--color-surface-low) rounded-full">
              <BarChart3 className="w-6 h-6 text-(--color-primary)" />
            </div>
            <h1 className="text-3xl font-bold tracking-tight font-display">Performance Reports</h1>
          </div>
          <p className="text-(--color-on-surface-variant) text-sm">Financial health overview and herd ROI analytics.</p>
        </div>
      </header>

      <ReportsUI initialData={data as any} equityData={equityData || []} />
      
      {/* Print-only footer */}
      <div className="hidden print:block text-center text-xs text-gray-400 mt-12 pt-8 border-t border-gray-100">
        <p>Generated by Khamar Khata Farm Management System</p>
        <p>Date: {new Date().toLocaleDateString()}</p>
      </div>
    </div>
  )
}
