import { db } from '@/db'
import { profiles } from '@/db/schema'
import { eq, sql } from 'drizzle-orm'
import { auth } from '@/auth'
import { ReportsUI } from './ReportsUI'
import { BarChart3 } from 'lucide-react'

export default async function ReportsPage(props: {
  searchParams: Promise<{ start?: string; end?: string; range?: string }>
}) {
  const searchParams = await props.searchParams
  const session = await auth()
  let userId = session?.user?.id

  if (!userId) {
    const [firstUser] = await db.select().from(profiles).limit(1)
    if (firstUser) userId = firstUser.id
  }

  const startDate = searchParams.start || null
  const endDate = searchParams.end || null

  let reportsData: any = null
  let equityData: any = []

  try {
    const reportsRes: any = await db.execute(sql`
      SELECT get_farm_reports(${userId}::uuid, ${startDate ? sql`${startDate}::date` : null}, ${endDate ? sql`${endDate}::date` : null}) as data
    `)
    if (reportsRes && reportsRes[0]?.data) {
      reportsData = reportsRes[0].data
    }

    const equityRes: any = await db.execute(sql`
      SELECT * FROM get_partner_equity_report(${userId}::uuid)
    `)
    if (equityRes) {
      equityData = equityRes
    }
  } catch (error: any) {
    console.error('Error fetching reports:', error)
    return (
      <div className="p-8 text-center bg-red-50 text-red-600 rounded-md">
        <p className="font-bold">Failed to load report data.</p>
        <p className="text-sm mt-1">{error?.message || 'Database error'}</p>
      </div>
    )
  }

  return (
    <div className="flex flex-col gap-8 max-w-5xl mx-auto w-full pb-20">
      <header className="flex flex-col md:flex-row md:items-end justify-between gap-4 print:hidden">
        <div>
          <div className="flex items-center gap-3 mb-1">
            <div className="p-2 bg-(--color-surface-low) rounded-full">
              <BarChart3 className="w-6 h-6 text-(--color-primary)" />
            </div>
            <h1 className="text-3xl font-bold tracking-tight font-display">Performance Reports</h1>
          </div>
          <p className="text-(--color-on-surface-variant) text-sm">Financial health overview and herd ROI analytics.</p>
        </div>
      </header>

      <ReportsUI initialData={reportsData} equityData={equityData} />
      
      {/* Print-only footer */}
      <div className="hidden print:block text-center text-xs text-gray-400 mt-12 pt-8 border-t border-gray-100">
        <p>Generated by Khamar Khata Farm Management System</p>
        <p>Date: {new Date().toLocaleDateString()}</p>
      </div>
    </div>
  )
}
